# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mingpian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('weixin', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=64, null=True)),
                ('phone_number_2', models.CharField(max_length=64, null=True)),
                ('address', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
