# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mingpian', '0003_auto_20160228_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Philosopherstone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mingpian.Mingpian')),
            ],
        ),
    ]
