# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mingpian', '0004_philosopherstone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philosopherstone',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
