# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mingpian', '0006_auto_20160229_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='philosopherstone',
            old_name='create_date',
            new_name='create_datetime',
        ),
    ]
