# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mingpian', '0007_auto_20160229_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosopherstone',
            name='player',
        ),
        migrations.DeleteModel(
            name='Philosopherstone',
        ),
    ]
